# Generated by Django 3.1.6 on 2021-02-05 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arrestee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(null=True)),
                ('last_name', models.TextField()),
                ('middle_name', models.TextField(null=True)),
                ('gender_code', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unknown/Unreported')], max_length=1, null=True)),
                ('race_code', models.CharField(choices=[('WHITE', 'White'), ('BLACK', 'Black'), ('UNREPORTED', 'Unknown/Unreported'), ('ASIAN', 'Asian'), ('ASIANgettextPACIFIC', 'Asian/Pacific Islander'), ('NATIVE', 'Native American/Alaskan Native'), ('BIRACIAL', 'Bi-Racial'), ('HAWAIIAN_PACIFIC', 'Native Hawaiian/Pacific Islander')], max_length=20, null=True)),
                ('birth_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otn', models.TextField(unique=True)),
                ('filed_date', models.DateField(null=True)),
                ('city', models.TextField(null=True)),
                ('county', models.TextField(null=True)),
                ('state', models.CharField(max_length=2, null=True)),
                ('zip', models.CharField(max_length=10, null=True)),
                ('disposition', models.TextField(null=True)),
                ('disposition_date', models.DateField(null=True)),
                ('disposing_judge', models.TextField(null=True)),
                ('arrestees', models.ManyToManyField(to='pa_court_archive.Arrestee')),
            ],
        ),
        migrations.CreateModel(
            name='Docket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docket_number', models.TextField(unique=True)),
                ('case', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pa_court_archive.case')),
            ],
        ),
        migrations.CreateModel(
            name='Offense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disposition', models.TextField(null=True)),
                ('date', models.DateField(null=True)),
                ('disposition_date', models.DateField(null=True)),
                ('description', models.TextField()),
                ('originating_sequence', models.IntegerField(null=True)),
                ('statute_type', models.CharField(choices=[('O', 'Ordinance'), ('S', 'Statute')], max_length=1, null=True)),
                ('statute_title', models.TextField(null=True)),
                ('statute_section', models.TextField(null=True)),
                ('statute_subsection', models.TextField(null=True)),
                ('inchoate_statute_title', models.TextField(null=True)),
                ('inchoate_statute_section', models.TextField(null=True)),
                ('inchoate_statute_subsection', models.TextField(null=True)),
                ('grade', models.CharField(max_length=2, null=True)),
                ('docket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pa_court_archive.docket')),
            ],
        ),
        migrations.AddIndex(
            model_name='arrestee',
            index=models.Index(fields=['last_name', 'first_name', 'middle_name'], name='pa_court_ar_last_na_2b9e34_idx'),
        ),
        migrations.AddIndex(
            model_name='arrestee',
            index=models.Index(fields=['birth_date'], name='pa_court_ar_birth_d_f75535_idx'),
        ),
        migrations.AddConstraint(
            model_name='arrestee',
            constraint=models.UniqueConstraint(condition=models.Q(first_name__isnull=True), fields=('last_name',), name='unique_lastname_per_null_firstname'),
        ),
        migrations.AddConstraint(
            model_name='arrestee',
            constraint=models.UniqueConstraint(condition=models.Q(('middle_name__isnull', True), ('birth_date__isnull', True)), fields=('last_name', 'first_name'), name='unique_lastname_firstname_per_null_middlename_null_birthdate'),
        ),
        migrations.AddConstraint(
            model_name='arrestee',
            constraint=models.UniqueConstraint(condition=models.Q(middle_name__isnull=True), fields=('last_name', 'first_name', 'birth_date'), name='unique_lastname_firstname_birthdate_per_null_middlename'),
        ),
        migrations.AddConstraint(
            model_name='arrestee',
            constraint=models.UniqueConstraint(condition=models.Q(birth_date__isnull=True), fields=('last_name', 'first_name', 'middle_name'), name='unique_fullname_per_null_birthdate'),
        ),
        migrations.AddConstraint(
            model_name='arrestee',
            constraint=models.UniqueConstraint(fields=('first_name', 'last_name', 'middle_name', 'birth_date'), name='unique_arrestee'),
        ),
        migrations.AddIndex(
            model_name='offense',
            index=models.Index(fields=['docket'], name='pa_court_ar_docket__ae04a5_idx'),
        ),
        migrations.AddIndex(
            model_name='docket',
            index=models.Index(fields=['docket_number'], name='pa_court_ar_docket__bf6fa0_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['otn'], name='pa_court_ar_otn_0ee051_idx'),
        ),
    ]
