# Generated by Django 2.2.5 on 2019-09-22 17:43
from django.db import migrations


def create_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')

    for name in ["Attorney", "Intern", "Volunteer"]:
        g = Group(name=name)
        g.save()


class Migration(migrations.Migration):
    """
    Build the three initial groups
    """
    dependencies = [
        ('auth', '0011_update_proxy_permissions')
    ]

    operations = [
        migrations.RunPython(create_groups),
    ]
