# Generated by Django 3.1.4 on 2020-12-19 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expunger', '0003_auto_20190930_0311'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocketMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_mysql_id', models.TextField(unique=True)),
                ('county_name', models.TextField()),
                ('docket_number', models.TextField()),
                ('filed_date', models.TextField()),
                ('last_name', models.TextField()),
                ('first_name', models.TextField()),
            ],
        ),
    ]
