# Generated by Django 3.1.4 on 2020-12-19 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expunger', '0004_docketmetadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docketmetadata',
            name='county_name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='docketmetadata',
            name='docket_number',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='docketmetadata',
            name='filed_date',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='docketmetadata',
            name='first_name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='docketmetadata',
            name='last_name',
            field=models.TextField(null=True),
        ),
    ]
