# Generated by Django 3.1.5 on 2021-01-22 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expunger', '0006_auto_20210109_0326'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DocketMetadata',
        ),
    ]
